site_name: 'ESL-Note'

site_description: 'The Elements of Statistical Learning(ESL) 中文版笔记，包括公式和习题的详细推导。'

site_author: bxdd

repo_name: 'bxdd/ESL-Note'
repo_url: 'https://github.com/bxdd/ESL-Note'

theme:
    name: material
    palette:
        primary: 'Blue'
        accent: 'Yellow'
    feature:
        tabs: false
    language: 'zh'


copyright: 'Copyright &copy; 2021-2026 bxdd'

markdown_extensions: 
    - admonition
    - codehilite:
        guess_lang: false
        linenums: false
    - toc:
        permalink: true
    - footnotes
    - meta
    - def_list
    - mdx_math:
        enable_dollar_delimiter: true


extra_javascript:
    - mathjax.js
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

